environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.2"
      PYTHON_ARCH: "64"

environment:
  matrix:
  - TOXENV: py37

build: off

install:
- pip install tox

test_script:
- tox

after_test:
- coverage report
