environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "64"

build: off

install:
- pip install -r requirements_dev.txt
- pip install pytest-cov
- pip install codecov

test_script:
- pytest --cov=sdf4sim tests

after_test:
- coverage report
- codecov --token "2cfbf1b1-71ee-4871-816b-04c97ea2fca9"
- ps: |
    # this uploads results.xml produced in test_script step
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\results.xml))