environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "64"
      TCL_LIBRARY: "C:\\Python34\tcl\tcl8.6"
      TK_LIBRARY: "C:\\Python34\\tcl\\tk8.6"

build: off

install:
- pip install tox
- pip install codecov

test_script:
- tox

after_test:
- codecov --token "2cfbf1b1-71ee-4871-816b-04c97ea2fca9"
