environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "64"
      TOXENV: py37

build: off

install:
- SET PATH=%PYTHON%;%path%
- pip install tox
- pip install codecov

test_script:
- tox

after_test:
- codecov --token "2cfbf1b1-71ee-4871-816b-04c97ea2fca9"

on_finish:
  # Upload test results to AppVeyor
  - ps: |
      # this uploads nosetests.xml produced in test_script step
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\results.xml))